import { ref } from "vue";

export interface ItemProps {
  title: string;
  stars: number;
  description: string;
  image: string;
  price: number;
  discount?: number;
  url: string;
  buy: () => void;

  category: string;
}

export interface ItemProps {
  title: string;
  stars: number;
  description: string;
  image: string;
  price: number;
  discount?: number;
  url: string;
  buy: () => void;
  category: string;
}

export const data: ItemProps[] = [
  {
    title: "Ergonomic Wooden Chair",
    stars: 4.5,
    description:
      "A comfortable and stylish wooden chair, perfect for your living room.",
    image: "/chair.png",
    price: 1200,
    discount: 15,
    url: "/chair.png",
    buy: () => console.log("Bought: Ergonomic Wooden Chair"),
    category: "Chair",
  },
  {
    title: "Modern Sofa",
    stars: 4.8,
    description: "Spacious modern sofa with soft fabric and minimalist design.",
    image: "/chair.png",
    price: 3500,
    discount: 20,
    url: "/chair.png",
    buy: () => console.log("Bought: Modern Sofa"),
    category: "Sofa",
  },
  {
    title: "Luxury Bed",
    stars: 5,
    description: "Premium king-sized bed with memory foam mattress included.",
    image: "/chair.png",
    price: 5000,
    url: "/chair.png",
    buy: () => console.log("Bought: Luxury Bed"),
    category: "Bed",
  },
  {
    title: "Office Desk",
    stars: 4.2,
    description: "Sleek and sturdy office desk with cable management system.",
    image: "/chair.png",
    price: 1800,
    discount: 10,
    url: "/chair.png",
    buy: () => console.log("Bought: Office Desk"),
    category: "Table",
  },
  {
    title: "Stylish Lamp",
    stars: 4.7,
    description: "Energy-efficient lamp with warm lighting and modern design.",
    image: "/chair.png",
    price: 350,
    url: "/chair.png",
    buy: () => console.log("Bought: Stylish Lamp"),
    category: "Lighting",
  },
  {
    title: "Bookshelf Organizer",
    stars: 4.6,
    description: "Spacious wooden bookshelf with adjustable shelves.",
    image: "/chair.png",
    price: 950,
    url: "/chair.png",
    buy: () => console.log("Bought: Bookshelf Organizer"),
    category: "Storage",
  },
  {
    title: "Minimalist Coffee Table",
    stars: 4.4,
    description: "Compact and modern coffee table made of oak wood.",
    image: "/chair.png",
    price: 750,
    discount: 5,
    url: "/chair.png",
    buy: () => console.log("Bought: Minimalist Coffee Table"),
    category: "Table",
  },
  {
    title: "Leather Recliner",
    stars: 4.9,
    description: "Luxurious leather recliner chair with full back support.",
    image: "/chair.png",
    price: 2800,
    discount: 12,
    url: "/chair.png",
    buy: () => console.log("Bought: Leather Recliner"),
    category: "Chair",
  },
  {
    title: "Dining Table Set",
    stars: 4.7,
    description: "Solid oak dining table with 6 comfortable chairs included.",
    image: "/chair.png",
    price: 4200,
    discount: 18,
    url: "/chair.png",
    buy: () => console.log("Bought: Dining Table Set"),
    category: "Dining",
  },
  {
    title: "Bean Bag Chair",
    stars: 4.3,
    description: "Cozy bean bag chair with soft microfiber fabric.",
    image: "/chair.png",
    price: 400,
    url: "/chair.png",
    buy: () => console.log("Bought: Bean Bag Chair"),
    category: "Chair",
  },
  {
    title: "Outdoor Patio Set",
    stars: 4.5,
    description: "Weather-resistant patio set with table and 4 chairs.",
    image: "/chair.png",
    price: 2500,
    discount: 25,
    url: "/chair.png",
    buy: () => console.log("Bought: Outdoor Patio Set"),
    category: "Outdoor",
  },
  {
    title: "Wall Shelf",
    stars: 4.1,
    description: "Floating wall shelf perfect for books or decor.",
    image: "/chair.png",
    price: 300,
    url: "/chair.png",
    buy: () => console.log("Bought: Wall Shelf"),
    category: "Storage",
  },
  {
    title: "Compact Nightstand",
    stars: 4.2,
    description: "Small wooden nightstand with two drawers.",
    image: "/chair.png",
    price: 600,
    url: "/chair.png",
    buy: () => console.log("Bought: Compact Nightstand"),
    category: "Table",
  },
  {
    title: "Sectional Sofa",
    stars: 4.9,
    description: "Large sectional sofa with plush cushions and storage space.",
    image: "/chair.png",
    price: 4800,
    discount: 22,
    url: "/chair.png",
    buy: () => console.log("Bought: Sectional Sofa"),
    category: "Sofa",
  },
  {
    title: "Kitchen Stool",
    stars: 4.0,
    description: "Metal and wood kitchen stool with footrest support.",
    image: "/chair.png",
    price: 350,
    url: "/chair.png",
    buy: () => console.log("Bought: Kitchen Stool"),
    category: "Chair",
  },
  {
    title: "Wardrobe Closet",
    stars: 4.8,
    description: "Spacious wardrobe closet with sliding mirrored doors.",
    image: "/chair.png",
    price: 3900,
    discount: 15,
    url: "/chair.png",
    buy: () => console.log("Bought: Wardrobe Closet"),
    category: "Storage",
  },
  {
    title: "Rocking Chair",
    stars: 4.6,
    description: "Classic wooden rocking chair with cushioned seating.",
    image: "/chair.png",
    price: 1100,
    url: "/chair.png",
    buy: () => console.log("Bought: Rocking Chair"),
    category: "Chair",
  },
  {
    title: "Workstation Set",
    stars: 4.7,
    description: "Complete workstation with desk, shelves, and drawers.",
    image: "/chair.png",
    price: 3200,
    discount: 10,
    url: "/chair.png",
    buy: () => console.log("Bought: Workstation Set"),
    category: "Office",
  },
  {
    title: "Vanity Table",
    stars: 4.5,
    description: "Elegant vanity table with mirror and storage compartments.",
    image: "/chair.png",
    price: 2100,
    url: "/chair.png",
    buy: () => console.log("Bought: Vanity Table"),
    category: "Table",
  },
  {
    title: "Accent Chair",
    stars: 4.4,
    description: "Stylish accent chair with soft velvet upholstery.",
    image: "/chair.png",
    price: 1350,
    discount: 8,
    url: "/chair.png",
    buy: () => console.log("Bought: Accent Chair"),
    category: "Chair",
  },
];

export const reviews = ref([
  {
    id: 1,
    name: "John Doe",
    avatar: "https://github.com/shadcn.png",
    fallback: "JD",
    date: "1 day ago",
    rating: 4.5,
    text: "Really impressed with the product quality. Would definitely buy again!",
  },
  {
    id: 2,
    name: "Alice Johnson",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    fallback: "AJ",
    date: "2 days ago",
    rating: 5,
    text: "Absolutely love this! Great quality and fast delivery. Highly recommend!",
  },
  {
    id: 3,
    name: "Michael Smith",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    fallback: "MS",
    date: "3 days ago",
    rating: 3.5,
    text: "Product is decent but packaging could be better. Expected more for the price.",
  },
  {
    id: 4,
    name: "Sophie Turner",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    fallback: "ST",
    date: "5 days ago",
    rating: 4,
    text: "Looks great and feels sturdy. Matches perfectly with my room decor.",
  },
  {
    id: 5,
    name: "Daniel Lee",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    fallback: "DL",
    date: "1 week ago",
    rating: 2.5,
    text: "Not very happy. The build quality could be improved and shipping was slow.",
  },
  {
    id: 6,
    name: "Emma Wilson",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    fallback: "EW",
    date: "1 week ago",
    rating: 5,
    text: "This is exactly what I needed! Super comfortable and stylish.",
  },
  {
    id: 7,
    name: "Chris Evans",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    fallback: "CE",
    date: "2 weeks ago",
    rating: 4.2,
    text: "Very satisfied overall. Some minor scratches but nothing too serious.",
  },
  {
    id: 8,
    name: "Linda Martinez",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    fallback: "LM",
    date: "3 weeks ago",
    rating: 3.8,
    text: "It does the job but I wish it had more color options. Still decent.",
  },
]);
