export interface ItemProps {
  title: string;
  stars: number;
  description: string;
  image: string;
  price: number;
  discount?: number;
  url: string;
  buy: () => void;
}

export const data: ItemProps[] = [
  {
    title: "Ergonomic Wooden Chair",
    stars: 4.5,
    description:
      "A comfortable and stylish wooden chair, perfect for your living room.",
    image: "/chair.png",
    price: 1200,
    discount: 15,
    url: "/chair.png",
    buy: () => console.log("Bought: Ergonomic Wooden Chair"),
  },
  {
    title: "Modern Sofa",
    stars: 4.8,
    description: "Spacious modern sofa with soft fabric and minimalist design.",
    image: "/chair.png",
    price: 3500,
    discount: 20,
    url: "/chair.png",
    buy: () => console.log("Bought: Modern Sofa"),
  },
  {
    title: "Luxury Bed",
    stars: 5,
    description: "Premium king-sized bed with memory foam mattress included.",
    image: "/chair.png",
    price: 5000,
    url: "/chair.png",
    buy: () => console.log("Bought: Luxury Bed"),
  },
  {
    title: "Office Desk",
    stars: 4.2,
    description: "Sleek and sturdy office desk with cable management system.",
    image: "/chair.png",
    price: 1800,
    discount: 10,
    url: "/chair.png",
    buy: () => console.log("Bought: Office Desk"),
  },
  {
    title: "Stylish Lamp",
    stars: 4.7,
    description: "Energy-efficient lamp with warm lighting and modern design.",
    image: "/chair.png",
    price: 350,
    url: "/chair.png",
    buy: () => console.log("Bought: Stylish Lamp"),
  },
  {
    title: "Bookshelf Organizer",
    stars: 4.6,
    description: "Spacious wooden bookshelf with adjustable shelves.",
    image: "/chair.png",
    price: 950,
    url: "/chair.png",
    buy: () => console.log("Bought: Bookshelf Organizer"),
  },
  {
    title: "Minimalist Coffee Table",
    stars: 4.4,
    description: "Compact and modern coffee table made of oak wood.",
    image: "/chair.png",
    price: 750,
    discount: 5,
    url: "/chair.png",
    buy: () => console.log("Bought: Minimalist Coffee Table"),
  },
  {
    title: "Leather Recliner",
    stars: 4.9,
    description: "Luxurious leather recliner chair with full back support.",
    image: "/chair.png",
    price: 2800,
    discount: 12,
    url: "/chair.png",
    buy: () => console.log("Bought: Leather Recliner"),
  },
  {
    title: "Dining Table Set",
    stars: 4.7,
    description: "Solid oak dining table with 6 comfortable chairs included.",
    image: "/chair.png",
    price: 4200,
    discount: 18,
    url: "/chair.png",
    buy: () => console.log("Bought: Dining Table Set"),
  },
  {
    title: "Bean Bag Chair",
    stars: 4.3,
    description: "Cozy bean bag chair with soft microfiber fabric.",
    image: "/chair.png",
    price: 400,
    url: "/chair.png",
    buy: () => console.log("Bought: Bean Bag Chair"),
  },
  {
    title: "Outdoor Patio Set",
    stars: 4.5,
    description: "Weather-resistant patio set with table and 4 chairs.",
    image: "/chair.png",
    price: 2500,
    discount: 25,
    url: "/chair.png",
    buy: () => console.log("Bought: Outdoor Patio Set"),
  },
  {
    title: "Wall Shelf",
    stars: 4.1,
    description: "Floating wall shelf perfect for books or decor.",
    image: "/chair.png",
    price: 300,
    url: "/chair.png",
    buy: () => console.log("Bought: Wall Shelf"),
  },
  {
    title: "Compact Nightstand",
    stars: 4.2,
    description: "Small wooden nightstand with two drawers.",
    image: "/chair.png",
    price: 600,
    url: "/chair.png",
    buy: () => console.log("Bought: Compact Nightstand"),
  },
  {
    title: "Sectional Sofa",
    stars: 4.9,
    description: "Large sectional sofa with plush cushions and storage space.",
    image: "/chair.png",
    price: 4800,
    discount: 22,
    url: "/chair.png",
    buy: () => console.log("Bought: Sectional Sofa"),
  },
  {
    title: "Kitchen Stool",
    stars: 4.0,
    description: "Metal and wood kitchen stool with footrest support.",
    image: "/chair.png",
    price: 350,
    url: "/chair.png",
    buy: () => console.log("Bought: Kitchen Stool"),
  },
  {
    title: "Wardrobe Closet",
    stars: 4.8,
    description: "Spacious wardrobe closet with sliding mirrored doors.",
    image: "/chair.png",
    price: 3900,
    discount: 15,
    url: "/chair.png",
    buy: () => console.log("Bought: Wardrobe Closet"),
  },
  {
    title: "Rocking Chair",
    stars: 4.6,
    description: "Classic wooden rocking chair with cushioned seating.",
    image: "/chair.png",
    price: 1100,
    url: "/chair.png",
    buy: () => console.log("Bought: Rocking Chair"),
  },
  {
    title: "Workstation Set",
    stars: 4.7,
    description: "Complete workstation with desk, shelves, and drawers.",
    image: "/chair.png",
    price: 3200,
    discount: 10,
    url: "/chair.png",
    buy: () => console.log("Bought: Workstation Set"),
  },
  {
    title: "Vanity Table",
    stars: 4.5,
    description: "Elegant vanity table with mirror and storage compartments.",
    image: "/chair.png",
    price: 2100,
    url: "/chair.png",
    buy: () => console.log("Bought: Vanity Table"),
  },
  {
    title: "Accent Chair",
    stars: 4.4,
    description: "Stylish accent chair with soft velvet upholstery.",
    image: "/chair.png",
    price: 1350,
    discount: 8,
    url: "/chair.png",
    buy: () => console.log("Bought: Accent Chair"),
  },
];
